### ISSUE TITLE
Publish Docker images for ARM architecture

### ISSUE THREAD

**Issue by ngosang** [bluet/docker-cronicle-docker#11]
You can publish images for other architectures. For example, RaspberryPi has an ARM processor.

Run:
```bash
docker buildx create --use
docker buildx build -t bluet/cronicle-docker:0.8.62-1 --platform linux/386,linux/amd64,linux/arm/v5,linux/arm/v7,linux/arm64/v8,linux/mips64le,linux/ppc64le,linux/s390x --push .
```

You will see something like that in DockerHub
![image](https://user-images.githubusercontent.com/10577978/136885169-9837c731-0017-4614-af16-1f77bc4a45c8.png)

**Comment by bluet** [comment]
done in https://github.com/bluet/docker-cronicle-docker/commit/82037838eb87708329efa0f2c33d683f9a5535bd  
result https://hub.docker.com/r/bluet/cronicle-docker/tags

But as official docker image supports only `linux/amd64` and `linux/arm64/v8` we supports those two too. https://hub.docker.com/_/docker?tab=tags
