### ISSUE TITLE
`.setup_done` file does not get saved to alternative storage locations

### ISSUE THREAD

**Issue by TheBestMoshe** [bluet/docker-cronicle-docker#18]
I set up Cronicle using this Docker image. However, I am using S3 as the storage backend. Since I am using S3 I am not mounting any data volumes to the container. 

The `.setup_done` file is being created only inside the Docker container. Whenever the container restarts, the setup scripts run and reset all the data which is stored in S3.

**Comment by bluet** [comment]
@TheBestMoshe any suggestions?

**Comment by bluet** [comment]
closing due to no further activities.
