### ISSUE TITLE
Forced reload of the custom configuration not works

### ISSUE THREAD

**Issue by sunnyworm** [bluet/docker-cronicle-docker#2]
#### Describe

I am trying to use a custom configuration, however I cannot change the config with the instructions.

#### To Reproduce:

1. Pull and Run the docker with the instructions in README.md
2. stop docker
3. Create a custom config [file](https://github.com/jhuckaby/Cronicle/blob/master/sample_conf/config.json) with url, http_port modified
4. cp the config to ...docker-cronicle-docker/data/config.json.import
5. remove the .setup_done file
6. restart the container

#### Result:

The port of cronicle did not change, and it says:

`Storage has already been set up.  There is no need to run this command again.`

#### Workarounds:

Build a image with custom Dockerfile and config.json.import :P

**Comment by bluet** [comment]
@sunnyworm ah... has this been fixed?

**Comment by bluet** [comment]
closing due to no further activities.
