### ISSUE TITLE
log_archive_path setting not clearing the old logs?

### ISSUE THREAD

**Issue by vikingtoby** [bluet/docker-cronicle-docker#23]
As I understand it from this issue on the main project: https://github.com/jhuckaby/Cronicle/issues/5

It should clear the logs `/opt/cronicle/data/logs/` when nightly maintenance runs if you've set the `log_archive_path` setting, this doesn't seem to be the case, and I can't find any errors regarding this?

**Comment by bluet** [comment]
I've pushed the updated 0.9.9, please help on testing it and see if the issue persists. Thanks.

https://github.com/bluet/docker-cronicle-docker/issues/24

**Comment by bluet** [comment]
closing due to no further activities.
