### ISSUE TITLE
New release 0.9.8

### ISSUE THREAD

**Issue by ngosang** [bluet/docker-cronicle-docker#24]
https://github.com/jhuckaby/Cronicle/releases/tag/v0.9.8

**Comment by ngosang** [comment]
Update 0.9.9

**Comment by bluet** [comment]
@ngosang thanks!

0.9.9 pushed.
- https://hub.docker.com/r/bluet/cronicle-docker/tags
- https://github.com/bluet/docker-cronicle-docker/releases/tag/0.9.9
