### ISSUE TITLE
PID file prevents Cronicle from starting

### ISSUE THREAD

**Issue by TinJoy59** [bluet/docker-cronicle-docker#25]
Whenever Cronicle exists improperly, the PID file remains in the logs directory and prevents from subsequent startup. 

I noticed there has been an issue with it already but I experience this on the latest version too. 

On start, old PID files are not removed.

Could you help me solve the issue or circumvent it?

**Comment by bluet** [comment]
@TinJoy59 is this related to #23 ?

**Comment by bluet** [comment]
I've pushed the updated 0.9.9, please help on testing it and see if the issue persists. Thanks.

https://github.com/bluet/docker-cronicle-docker/issues/24

**Comment by TinJoy59** [comment]
Yes, thank you. The PID files is now removed upon start.
