### ISSUE TITLE
Create Event from Dockerfile

### ISSUE THREAD

**Issue by jas1989** [bluet/docker-cronicle-docker#27]
Hi to everyone, I'd like to know if it possible to write a file for an event and copy it during docker build.

In other word, I have the following Dockerfie:

``` yaml
FROM bluet/cronicle-docker
COPY ./plugins /opt/cronicle/plugins
EXPOSE 3012
```

Is it possible to create event and load to my image like my plugins folder?

Thanks

**Comment by bluet** [comment]
Hi @jas1989 , sorry I do not quite understanding what "event" you mean.

If you want to mount a local folder to `/opt/cronicle/plugins` in the container, your can use `-v $PWD/plugins:/opt/cronicle/plugins:rw`.

Ref: https://github.com/bluet/docker-cronicle-docker#running

**Comment by jas1989** [comment]
Hi @bluet, mount a local folder it's fine. Thank you
