### ISSUE TITLE
[bug] Cronicle setup executed on original config and not the provided one

### ISSUE THREAD

**Issue by peterbuga** [bluet/docker-cronicle-docker#36]
this line should be before setup command https://github.com/bluet/docker-cronicle-docker/blob/master/docker/entrypoint.sh#L24

on a fresh start, the original config is executed i.e. the setup is done on local filesystem is instead S3 is defined and a manual setup command needs to be triggered in order to make everything play nice

**Comment by bluet** [comment]
hi @peterbuga for the "provided one" do you mean via env variables or through `/path-to-cronicle-storage/data/config.json.import`?

**Comment by peterbuga** [comment]
sorry for that @bluet (wrote the message in a small rush to not forget about it)

yes, you are right. using this option https://github.com/bluet/docker-cronicle-docker#custom-configuration-file the image provided `config.json` will be executed first for initialization and then the `config.json.import` one.

my basic fix right now was to simply mount over the `/opt/cronicle/conf/config.json` file and let the setup use that. i'm aware this might not happen too often but in the same time the fix is easy too (i think, didn't test it too much)

i could do a small PR if you're willing to look into it

**Comment by bluet** [comment]
@peterbuga cool, a PR could clarify many things.
