### ISSUE TITLE
Running Cronicle setup before importing config?

### ISSUE THREAD

**Issue by dsturgilljr** [bluet/docker-cronicle-docker#38]
I noticed in the entrypoint.sh that the custom config is moved into place after the setup is run. I am building a Cronicle server that uses S3 storage, and I was having issues until I moved the setup after moving the custom config in place. I was just reaching out to see if this was tested with a custom config as I was not able to achieve the desired result without the aforementioned change to the entrypoint.sh.

Looking forward to your response! Thanks!

**Comment by peterbuga** [comment]
@dsturgilljr it just so happens I had the exact same problem, see [this](https://github.com/bluet/docker-cronicle-docker/issues/36) and [this PR](https://github.com/bluet/docker-cronicle-docker/pull/39)

hopefully @bluet will approve it  🤞

**Comment by dsturgilljr** [comment]
This is a worthy change. I understand that the config is hot reloaded but having setup run after the custom config is moved into place is important (required really) for external storage to work properly on initial setup.
