### ISSUE TITLE
unable to import cronicle data backup

### ISSUE THREAD

**Issue by akanealw** [bluet/docker-cronicle-docker#41]
Per [this](https://github.com/jhuckaby/Cronicle/blob/master/docs/CommandLine.md#data-import-and-export) option on the main repository, you can import a data config to a new master. I tried doing the import from inside the container and got this error.

> /opt/cronicle # /opt/cronicle/bin/storage-cli.js import /opt/cronicle/data/cronicle-data-backup.txt
ERROR: Please stop Cronicle before running this script.

If I stop cronicle by running /opt/cronicle/bin/control.sh stop inside the container it kills the container and the import is not completed.

**Comment by bluet** [comment]
@akanealw try something like this `docker run -it -v /var/run/docker.sock:/var/run/docker.sock --hostname localhost -p 3012:3012 --name cronicle bluet/cronicle-docker:latest bash` and you'll get a bash.
Then you can do whatever you want. :+1: 

If this helps, please close the issue, or reply if it doesn't.

**Comment by akanealw** [comment]
That worked just fine. Just had to add a local volume bind with my import data and I ran /opt/cronicle/bin/storage-cli.js import /import/cronicle-backup.txt successfully.

Thanks!
