### ISSUE TITLE
Add environment variable for default text editor

### ISSUE THREAD

**Issue by ngosang** [bluet/docker-cronicle-docker#8]
Following https://github.com/jhuckaby/Cronicle/issues/36 , at some point I had to execute Cronicle CLI..
If you run `/opt/cronicle/bin/storage-cli.js edit global/server_groups/0` you get an error: The editor is not set.
You can set this env var in the Dockerfile:
`EDITOR=vi`

**Comment by bluet** [comment]
users can set ENV while docker run, but yes I agree that it won't hurt setting a default ENV.

As most users are not that familiar with `vi` (more with vim), maybe use `pico` as default?

**Comment by ngosang** [comment]
I agree that vi is complicated but pico and nano are not available in the containe, just vi
